### ZSH Config #{{{

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="bira"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(\
 autojump\
 bower\
 brew\
 colored-man\
 common-aliases\
 composer\
 gem\
 git\
 git-extras\
 node\
 npm\
 osx\
 pip\
 ruby\
 rbenv\
 ssh-agent\
 sublime\
 symfony2\
 vagrant\
 web-search\
)

#}}}
### General Config #{{{

# Save a ton of history
HISTSIZE=20000
HISTFILE=~/.zsh_history
SAVEHIST=20000

# Enable completion
autoload -U compinit
compinit

# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef

# automatically pushd
setopt auto_pushd
export dirstacksize=5

#}}}
### Configure PATH #{{{

### Add ~/.bin to path
PATH="$PATH:$HOME/.bin"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

### Add VMWare Fusion Commands
export PATH="/Applications/VMware Fusion.app/Contents/Library:$PATH"

#}}}
### Import Aliases #{{{

# NOTE: This must be BEFORE the GNU Coreutils are added to the PATH
#       or dircolors will not properly function
[[ -f ~/.aliases ]] && source ~/.aliases

#}}}
### ENV Vars #{{{

# Set default editor
export EDITOR=vim

### Default vagrant provider
export VAGRANT_DEFAULT_PROVIDER=vmware_fusion

### Fix ruby gem installation errors
export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future

#}}}
### Bootstrap Environment/Libs #{{{

### Load boxen
source /opt/boxen/env.sh

### alias git to hub command
### see  https://github.com/github/hub
eval "$(hub alias -s)"

# added by travis gem
[ -f /Users/steven/.travis/travis.sh ] && source /Users/steven/.travis/travis.sh

#}}}
### GNU Utils Setup #{{{

# setup GNU Coreutils
export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"

# Configure LS Colors
# NOTE: Make sure this is after GNU Utils are added to the path
eval $(dircolors ~/src/llwt/dircolors-solarized/dircolors.256dark)
#LSCOLORS='exfxcxdxbxegedabagacad'
#export LS_COLORS="di=34;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

#}}}

# Load oh-my-zsh...
source $ZSH/oh-my-zsh.sh
