# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="bira"

# Hide user unless we aren't the default
DEFAULT_USER="steven"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(autojump bower brew colored-man composer gem git git-extras osx pip ruby rbenv ssh-agent sublime symfony2 vagrant web-search)

source $ZSH/oh-my-zsh.sh

# Someting is resetting LSCOLORS, TODO: Figure out what it is when I have time, for now reset it
#                                       to the default
LSCOLORS='exfxcxdxbxegedabagacad'

# automatically pushd
setopt auto_pushd
export dirstacksize=5

# aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# Add ~/.bin to path
PATH="$PATH:$HOME/.bin"

export EDITOR=vim

### Default vagrant provider
export VAGRANT_DEFAULT_PROVIDER=vmware_fusion

### Fix ruby gem installation errors
export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future

### Load boxen
source /opt/boxen/env.sh

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
